/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2025-12-08 02:40:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>学生社会实践管理系统 - 首页</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background-color: #f0f2f5;\n");
      out.write("        }\n");
      out.write("        .header {\n");
      out.write("            background-color: #1890ff;\n");
      out.write("            color: white;\n");
      out.write("            padding: 15px 20px;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .header h1 {\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 20px;\n");
      out.write("        }\n");
      out.write("        .header .user-info {\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        .header .user-info a {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin-left: 15px;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            display: flex;\n");
      out.write("            height: calc(100vh - 60px);\n");
      out.write("        }\n");
      out.write("        .sidebar {\n");
      out.write("            width: 200px;\n");
      out.write("            background-color: #fff;\n");
      out.write("            border-right: 1px solid #e8e8e8;\n");
      out.write("            padding: 20px 0;\n");
      out.write("        }\n");
      out.write("        .sidebar-menu {\n");
      out.write("            list-style: none;\n");
      out.write("            padding: 0;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        .sidebar-menu li {\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("        }\n");
      out.write("        .sidebar-menu a {\n");
      out.write("            display: block;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            color: #333;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("        }\n");
      out.write("        .sidebar-menu a:hover {\n");
      out.write("            background-color: #e6f7ff;\n");
      out.write("            color: #1890ff;\n");
      out.write("        }\n");
      out.write("        .content {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 20px;\n");
      out.write("            overflow-y: auto;\n");
      out.write("        }\n");
      out.write("        .welcome-section {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 40px;\n");
      out.write("            box-shadow: 0 2px 12px 0 rgba(0,0,0,0.1);\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .welcome-section h2 {\n");
      out.write("            color: #333;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("        .welcome-section p {\n");
      out.write("            color: #666;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        .function-cards {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("        .function-card {\n");
      out.write("            background-color: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 30px;\n");
      out.write("            box-shadow: 0 2px 12px 0 rgba(0,0,0,0.1);\n");
      out.write("            text-align: center;\n");
      out.write("            transition: transform 0.3s;\n");
      out.write("        }\n");
      out.write("        .function-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("        }\n");
      out.write("        .function-card .icon {\n");
      out.write("            font-size: 48px;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("            color: #1890ff;\n");
      out.write("        }\n");
      out.write("        .function-card h3 {\n");
      out.write("            margin: 0 0 10px 0;\n");
      out.write("            color: #333;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("        .function-card p {\n");
      out.write("            margin: 0;\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"header\">\n");
      out.write("        <h1>学生社会实践管理系统</h1>\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <span>欢迎您，");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("            <a href=\"/user/logout\">退出登录</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <ul class=\"sidebar-menu\">\n");
      out.write("                <li><a href=\"/index\">首页</a></li>\n");
      out.write("                <li><a href=\"/student/list\">学生管理</a></li>\n");
      out.write("                <li><a href=\"/teacher/list\">教师管理</a></li>\n");
      out.write("                <li><a href=\"/activity/list\">实践活动管理</a></li>\n");
      out.write("                <li><a href=\"/studentActivity/list\">活动报名管理</a></li>\n");
      out.write("                <li><a href=\"/report/list\">实践报告管理</a></li>\n");
      out.write("                <li><a href=\"/grade/list\">成绩管理</a></li>\n");
      out.write("                <li><a href=\"/notice/list\">公告管理</a></li>\n");
      out.write("                <li><a href=\"/log/list\">系统日志</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"content\">\n");
      out.write("            <div class=\"welcome-section\">\n");
      out.write("                <h2>欢迎使用学生社会实践管理系统</h2>\n");
      out.write("                <p>本系统为学校提供学生社会实践活动的全面管理解决方案，包括活动发布、学生报名、实践报告提交、成绩评定等功能。</p>\n");
      out.write("                <div style=\"margin-top: 30px;\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/teacher/list\" style=\"padding: 10px 20px; margin: 0 10px; background-color: #1890ff; color: white; text-decoration: none; border-radius: 4px;\">教师管理</a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activity/list\" style=\"padding: 10px 20px; margin: 0 10px; background-color: #52c41a; color: white; text-decoration: none; border-radius: 4px;\">实践活动管理</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"function-cards\">\n");
      out.write("                <div class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">📚</div>\n");
      out.write("                    <h3>学生管理</h3>\n");
      out.write("                    <p>管理学生信息和档案</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">👨‍🏫</div>\n");
      out.write("                    <h3>教师管理</h3>\n");
      out.write("                    <p>管理教师信息和权限</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">🎯</div>\n");
      out.write("                    <h3>活动管理</h3>\n");
      out.write("                    <p>发布和管理实践活动</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">📝</div>\n");
      out.write("                    <h3>报告管理</h3>\n");
      out.write("                    <p>管理学生实践报告</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
