/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2025-12-12 15:59:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/develop/apache-maven-3.9.9/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/1.2.6/jakarta.servlet.jsp.jstl-1.2.6.jar!/META-INF/c.tld", Long.valueOf(1548318066000L));
    _jspx_dependants.put("file:/F:/develop/apache-maven-3.9.9/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/1.2.6/jakarta.servlet.jsp.jstl-1.2.6.jar", Long.valueOf(1765179676160L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>学生首页 - 学生社会实践管理系统</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            background-color: #f0f2f5;\n");
      out.write("        }\n");
      out.write("        .header {\n");
      out.write("            background-color: #1890ff;\n");
      out.write("            color: white;\n");
      out.write("            padding: 15px 20px;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .user-info {\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        .user-info a {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin-left: 15px;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            display: flex;\n");
      out.write("            min-height: calc(100vh - 60px);\n");
      out.write("        }\n");
      out.write("        .sidebar {\n");
      out.write("            width: 200px;\n");
      out.write("            background-color: #fff;\n");
      out.write("            box-shadow: 2px 0 8px rgba(0,0,0,0.08);\n");
      out.write("        }\n");
      out.write("        .sidebar-menu {\n");
      out.write("            list-style: none;\n");
      out.write("            padding: 20px 0;\n");
      out.write("        }\n");
      out.write("        .sidebar-menu li {\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("        .sidebar-menu a {\n");
      out.write("            display: block;\n");
      out.write("            padding: 12px 20px;\n");
      out.write("            color: #333;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("        }\n");
      out.write("        .sidebar-menu a:hover, .sidebar-menu a.active {\n");
      out.write("            background-color: #e6f7ff;\n");
      out.write("            color: #1890ff;\n");
      out.write("            border-right: 3px solid #1890ff;\n");
      out.write("        }\n");
      out.write("        .content {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("        .welcome-card {\n");
      out.write("            background-color: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 30px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.08);\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        .welcome-card h2 {\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("        .welcome-card p {\n");
      out.write("            color: #666;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("        .function-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .function-card {\n");
      out.write("            background-color: #fff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 30px;\n");
      out.write("            box-shadow: 0 2px 12px rgba(0,0,0,0.08);\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            cursor: pointer;\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: inherit;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        .function-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 4px 20px rgba(0,0,0,0.15);\n");
      out.write("        }\n");
      out.write("        .function-card .icon {\n");
      out.write("            font-size: 48px;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        .function-card h3 {\n");
      out.write("            margin: 0 0 10px 0;\n");
      out.write("            color: #333;\n");
      out.write("            font-size: 18px;\n");
      out.write("        }\n");
      out.write("        .function-card p {\n");
      out.write("            margin: 0;\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 14px;\n");
      out.write("            line-height: 1.6;\n");
      out.write("        }\n");
      out.write("        .stats-section {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        .stat-card {\n");
      out.write("            background-color: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 20px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.08);\n");
      out.write("        }\n");
      out.write("        .stat-card .number {\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #1890ff;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("        }\n");
      out.write("        .stat-card .label {\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"header\">\n");
      out.write("        <h1>学生社会实践管理系统 - 学生端</h1>\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <span>欢迎您，");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("            <a href=\"/user/logout\">退出登录</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <ul class=\"sidebar-menu\">\n");
      out.write("                <li><a href=\"/index\">首页</a></li>\n");
      out.write("                <li><a href=\"/activity/list\">实践活动</a></li>\n");
      out.write("                <li><a href=\"/studentActivity/myActivities\">我的活动</a></li>\n");
      out.write("                <li><a href=\"/group/manage\">小组管理</a></li>\n");
      out.write("                <li><a href=\"/dailyTask/myTasks\">日常任务</a></li>\n");
      out.write("                <li><a href=\"/practiceReport/list\">实践报告</a></li>\n");
      out.write("                <li><a href=\"/grade/view\">我的成绩</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"content\">\n");
      out.write("            <div class=\"welcome-card\">\n");
      out.write("                <h2>欢迎回来，");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("！</h2>\n");
      out.write("                <p>这里是您的学生工作台，您可以在这里查看实践活动、管理日常任务、提交实践报告等。</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"stats-section\">\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"number\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registeredActivityCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                    <div class=\"label\">已报名活动</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"number\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pendingTaskCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                    <div class=\"label\">待完成任务</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"number\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${submittedReportCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                    <div class=\"label\">已提交报告</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"function-grid\">\n");
      out.write("                <a href=\"/activity/list\" class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">🔍</div>\n");
      out.write("                    <h3>浏览实践活动</h3>\n");
      out.write("                    <p>查看所有可报名的社会实践活动，了解活动详情和要求</p>\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"/studentActivity/myActivities\" class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">📋</div>\n");
      out.write("                    <h3>我的活动</h3>\n");
      out.write("                    <p>查看已报名的活动，进行改选或退选操作</p>\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"/group/manage\" class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">👥</div>\n");
      out.write("                    <h3>小组管理</h3>\n");
      out.write("                    <p>从已报名的活动中选择，创建或加入实践小组，与同学协作完成实践活动</p>\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"/dailyTask/myTasks\" class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">✅</div>\n");
      out.write("                    <h3>日常任务</h3>\n");
      out.write("                    <p>填写和提交日常任务完成情况，记录实践过程</p>\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"/practiceReport/list\" class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">📝</div>\n");
      out.write("                    <h3>实践报告</h3>\n");
      out.write("                    <p>提交实践报告，查看教师反馈和评语</p>\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"/grade/view\" class=\"function-card\">\n");
      out.write("                    <div class=\"icon\">📊</div>\n");
      out.write("                    <h3>我的成绩</h3>\n");
      out.write("                    <p>查看实践活动成绩和教师评语</p>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
