/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2025-12-14 15:23:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.importExport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class importTeachers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/develop/apache-maven-3.9.9/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/1.2.6/jakarta.servlet.jsp.jstl-1.2.6.jar!/META-INF/c.tld", Long.valueOf(1548318066000L));
    _jspx_dependants.put("file:/F:/develop/apache-maven-3.9.9/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/1.2.6/jakarta.servlet.jsp.jstl-1.2.6.jar", Long.valueOf(1765161599120L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>导入教师 - 社会实践管理系统</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            max-width: 800px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 15px;\n");
      out.write("            box-shadow: 0 20px 40px rgba(0,0,0,0.1);\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header {\n");
      out.write("            background: linear-gradient(135deg, #2196F3 0%, #1976D2 100%);\n");
      out.write("            color: white;\n");
      out.write("            padding: 30px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header h1 {\n");
      out.write("            font-size: 28px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header p {\n");
      out.write("            font-size: 16px;\n");
      out.write("            opacity: 0.9;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .content {\n");
      out.write("            padding: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .upload-area {\n");
      out.write("            border: 3px dashed #2196F3;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 40px;\n");
      out.write("            text-align: center;\n");
      out.write("            background: #f8f9fa;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .upload-area:hover {\n");
      out.write("            border-color: #1976D2;\n");
      out.write("            background: #e3f2fd;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .upload-area.dragover {\n");
      out.write("            border-color: #4CAF50;\n");
      out.write("            background: #e8f5e8;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .upload-icon {\n");
      out.write("            font-size: 48px;\n");
      out.write("            color: #2196F3;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .upload-text {\n");
      out.write("            font-size: 18px;\n");
      out.write("            color: #333;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .upload-subtext {\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #666;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .file-input {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: linear-gradient(135deg, #2196F3 0%, #1976D2 100%);\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            padding: 12px 30px;\n");
      out.write("            border-radius: 25px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(33, 150, 243, 0.4);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background: #6c757d;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: inline-block;\n");
      out.write("            margin-right: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background: #5a6268;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .format-info {\n");
      out.write("            background: #e3f2fd;\n");
      out.write("            border-left: 4px solid #2196F3;\n");
      out.write("            padding: 20px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .format-info h3 {\n");
      out.write("            color: #1976D2;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .format-info ul {\n");
      out.write("            margin-left: 20px;\n");
      out.write("            color: #555;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .format-info li {\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-area {\n");
      out.write("            display: none;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-bar {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 20px;\n");
      out.write("            background: #e0e0e0;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-fill {\n");
      out.write("            height: 100%;\n");
      out.write("            background: linear-gradient(135deg, #2196F3 0%, #1976D2 100%);\n");
      out.write("            width: 0%;\n");
      out.write("            transition: width 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .progress-text {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 10px;\n");
      out.write("            color: #666;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .result-area {\n");
      out.write("            display: none;\n");
      out.write("            margin-top: 30px;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .result-success {\n");
      out.write("            background: #d4edda;\n");
      out.write("            border: 1px solid #c3e6cb;\n");
      out.write("            color: #155724;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .result-error {\n");
      out.write("            background: #f8d7da;\n");
      out.write("            border: 1px solid #f5c6cb;\n");
      out.write("            color: #721c24;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-list {\n");
      out.write("            max-height: 200px;\n");
      out.write("            overflow-y: auto;\n");
      out.write("            background: white;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            padding: 15px;\n");
      out.write("            margin-top: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-item {\n");
      out.write("            padding: 5px 0;\n");
      out.write("            border-bottom: 1px solid #eee;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-item:last-child {\n");
      out.write("            border-bottom: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .actions {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"header\">\n");
      out.write("            <h1>📥 导入教师名单</h1>\n");
      out.write("            <p>通过CSV文件批量导入教师信息</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"content\">\n");
      out.write("            <div class=\"format-info\">\n");
      out.write("                <h3>文件格式要求</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>文件格式：CSV（逗号分隔）</li>\n");
      out.write("                    <li>编码格式：UTF-8</li>\n");
      out.write("                    <li>必需字段：工号、姓名、性别、部门、职务</li>\n");
      out.write("                    <li>可选字段：手机号、邮箱</li>\n");
      out.write("                    <li>示例格式：工号,姓名,性别,部门,职务,手机号,邮箱</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"upload-area\" id=\"uploadArea\">\n");
      out.write("                <div class=\"upload-icon\">📁</div>\n");
      out.write("                <div class=\"upload-text\">点击选择文件或拖拽文件到此处</div>\n");
      out.write("                <div class=\"upload-subtext\">支持 CSV 文件，最大 5MB</div>\n");
      out.write("                <input type=\"file\" id=\"fileInput\" class=\"file-input\" accept=\".csv\" />\n");
      out.write("                <button class=\"btn-primary\" onclick=\"document.getElementById('fileInput').click()\">选择文件</button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"progress-area\" id=\"progressArea\">\n");
      out.write("                <div class=\"progress-bar\">\n");
      out.write("                    <div class=\"progress-fill\" id=\"progressFill\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"progress-text\" id=\"progressText\">正在上传...</div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"result-area\" id=\"resultArea\">\n");
      out.write("                <div id=\"resultContent\"></div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"actions\">\n");
      out.write("                <a href=\"/index\" class=\"btn-secondary\">返回首页</a>\n");
      out.write("                <a href=\"/teacher/list\" class=\"btn-secondary\">查看教师列表</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        const uploadArea = document.getElementById('uploadArea');\n");
      out.write("        const fileInput = document.getElementById('fileInput');\n");
      out.write("        const progressArea = document.getElementById('progressArea');\n");
      out.write("        const progressFill = document.getElementById('progressFill');\n");
      out.write("        const progressText = document.getElementById('progressText');\n");
      out.write("        const resultArea = document.getElementById('resultArea');\n");
      out.write("        const resultContent = document.getElementById('resultContent');\n");
      out.write("\n");
      out.write("        // 拖拽上传\n");
      out.write("        uploadArea.addEventListener('dragover', (e) => {\n");
      out.write("            e.preventDefault();\n");
      out.write("            uploadArea.classList.add('dragover');\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        uploadArea.addEventListener('dragleave', () => {\n");
      out.write("            uploadArea.classList.remove('dragover');\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        uploadArea.addEventListener('drop', (e) => {\n");
      out.write("            e.preventDefault();\n");
      out.write("            uploadArea.classList.remove('dragover');\n");
      out.write("            const files = e.dataTransfer.files;\n");
      out.write("            if (files.length > 0) {\n");
      out.write("                handleFile(files[0]);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // 文件选择\n");
      out.write("        fileInput.addEventListener('change', (e) => {\n");
      out.write("            if (e.target.files.length > 0) {\n");
      out.write("                handleFile(e.target.files[0]);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function handleFile(file) {\n");
      out.write("            // 验证文件类型\n");
      out.write("            if (!file.name.toLowerCase().endsWith('.csv')) {\n");
      out.write("                alert('请选择CSV文件');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            // 验证文件大小（5MB）\n");
      out.write("            if (file.size > 5 * 1024 * 1024) {\n");
      out.write("                alert('文件大小不能超过5MB');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            uploadFile(file);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function uploadFile(file) {\n");
      out.write("            const formData = new FormData();\n");
      out.write("            formData.append('file', file);\n");
      out.write("\n");
      out.write("            // 显示进度条\n");
      out.write("            uploadArea.style.display = 'none';\n");
      out.write("            progressArea.style.display = 'block';\n");
      out.write("            resultArea.style.display = 'none';\n");
      out.write("\n");
      out.write("            // 模拟进度\n");
      out.write("            let progress = 0;\n");
      out.write("            const progressInterval = setInterval(() => {\n");
      out.write("                progress += Math.random() * 20;\n");
      out.write("                if (progress > 90) progress = 90;\n");
      out.write("                progressFill.style.width = progress + '%';\n");
      out.write("            }, 200);\n");
      out.write("\n");
      out.write("            fetch('/importExport/importTeachers', {\n");
      out.write("                method: 'POST',\n");
      out.write("                body: formData\n");
      out.write("            })\n");
      out.write("            .then(response => response.json())\n");
      out.write("            .then(data => {\n");
      out.write("                clearInterval(progressInterval);\n");
      out.write("                progressFill.style.width = '100%';\n");
      out.write("                progressText.textContent = '上传完成';\n");
      out.write("\n");
      out.write("                setTimeout(() => {\n");
      out.write("                    showResult(data);\n");
      out.write("                }, 500);\n");
      out.write("            })\n");
      out.write("            .catch(error => {\n");
      out.write("                clearInterval(progressInterval);\n");
      out.write("                showResult({\n");
      out.write("                    success: false,\n");
      out.write("                    message: '上传失败：' + error.message\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function showResult(data) {\n");
      out.write("            progressArea.style.display = 'none';\n");
      out.write("            resultArea.style.display = 'block';\n");
      out.write("\n");
      out.write("            if (data.success) {\n");
      out.write("                let html = '<div class=\"result-success\">' +\n");
      out.write("                    '<h3>✅ 导入成功</h3>' +\n");
      out.write("                    '<p>' + (data.message || '') + '</p>' +\n");
      out.write("                    '<p>成功导入：' + (data.successCount || 0) + ' 条</p>' +\n");
      out.write("                    '<p>失败：' + (data.failCount || 0) + ' 条</p>';\n");
      out.write("\n");
      out.write("                if (data.errors && data.errors.length > 0) {\n");
      out.write("                    html += '<div class=\"error-list\">' +\n");
      out.write("                        '<h4>错误详情：</h4>';\n");
      out.write("                    for (let i = 0; i < data.errors.length; i++) {\n");
      out.write("                        html += '<div class=\"error-item\">' + data.errors[i] + '</div>';\n");
      out.write("                    }\n");
      out.write("                    html += '</div>';\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                html += '</div>';\n");
      out.write("                resultContent.innerHTML = html;\n");
      out.write("            } else {\n");
      out.write("                resultContent.innerHTML = '<div class=\"result-error\">' +\n");
      out.write("                    '<h3>❌ 导入失败</h3>' +\n");
      out.write("                    '<p>' + (data.message || '未知错误') + '</p>' +\n");
      out.write("                    '</div>';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
